### ISSUE TITLE
Planning Phase

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/quran#2]
estm time : 90mins
Time taken: 40mins

**imp issues to be fixed:**

- [x]  Spinner: https://github.com/fawazahmed0/askgod/issues/37 (estm: 30mins ,time take: 50mins)
- [x]  mir org: create a org trans in qapi to avoid misunderstands (change checkduplicate to true) (15mins)  (timetaken 8mins)
- [x]  CI breaking: https://github.com/fawazahmed0/askgod/issues/38 (update cron & noofQues)  (45mins) (timetaken 15mins)

**read/demo site with integration:**
**UI:**

- [x] Fixed upper panel with trans, chap,ver selection option (have labels) (2hrs)
- [x] change trans based on option selected
     - [ ] Show translations, append new trans (ordered)
- [ ] Add tooltip to indicate the edition-language etc

- [ ] cookies to remember settings (1hr)
- [x] indicate verse number with trans (30mins)
- [ ] Set fonts for specific versions (1hr)
- [ ] increase text size option (zoom in /out option /symbol) (30mins)
- [ ] URL to set edition (30mins)
- [ ] option to go specific ver using url & also indicate url on verse change (#5:1) (eg: chap 5 selected show, #5:1) (1hrs)
- [ ] Add to home screen (10mins)
- [ ] Little doc about website link etc(10mins)
- [ ] Add donate/share button (15mins)

- [ ] Add chapter with names (https://raw.githubusercontent.com/fawazahmed0/quran-api/1/info.min.json)
- [ ] optimize by fetching only chap, and adding ver effciently (use classes)
- [ ] fix anchor scroll issue: https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

**Not now:**
- [ ]  feature using reddit : https://github.com/fawazahmed0/askgod/issues/39  (1hr)

**Estm**: 570mins
With buffer : 670mins (11hrs) 07-12-20

**Comment by fawazahmed0** [comment]
**UI Design:**
![demosite](https://user-images.githubusercontent.com/20347013/101279716-1a6a9680-37ea-11eb-8b3a-835d44dd2330.png)
